import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fireEvent, render, screen, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { Explainability } from "../pages/Explainability";
import { snapshot } from "../data/snapshot";

describe("Explainability — scenario switching", () => {
  it("defaults to WEBHOOK_AMBIGUITY and switches between all three scenarios", () => {
    render(<Explainability />);
    expect(screen.getAllByText("WEBHOOK_AMBIGUITY").length).toBeGreaterThan(0);

    fireEvent.click(screen.getByRole("button", { name: "INFRASTRUCTURE / HIGH CONFIDENCE" }));
    expect(screen.getAllByText("INFRASTRUCTURE").length).toBeGreaterThan(0);
    expect(screen.getAllByText("DEFER_RETRY").length).toBeGreaterThan(0);

    fireEvent.click(screen.getByRole("button", { name: "INFRASTRUCTURE / LOW CONFIDENCE" }));
    expect(screen.getAllByText("HUMAN_REVIEW").length).toBeGreaterThan(0);
  });
});

describe("Explainability — structured fields match the snapshot exactly", () => {
  it("WEBHOOK_AMBIGUITY: root cause, probability, action, reason", () => {
    render(<Explainability />);
    const s = snapshot.day14.scenarios.webhook_ambiguity;
    const summarySection = screen.getByRole("heading", { name: /decision summary/i }).closest("section");
    const scoped = within(summarySection as HTMLElement);
    expect(scoped.getByText(s.prediction.rootCause)).toBeInTheDocument();
    expect(scoped.getByText(s.policy.action)).toBeInTheDocument();
    expect(scoped.getByText(new RegExp(s.prediction.probability.toFixed(4)))).toBeInTheDocument();
    expect(scoped.getByText(new RegExp(s.policy.reason))).toBeInTheDocument();
  });

  it("infrastructure high confidence: threshold displayed, not hardcoded", () => {
    render(<Explainability />);
    fireEvent.click(screen.getByRole("button", { name: "INFRASTRUCTURE / HIGH CONFIDENCE" }));
    const s = snapshot.day14.scenarios.infrastructure_high_confidence;
    expect(s.policy.thresholdIfApplicable).toBe(0.75);
    expect(screen.getByText(/threshold 75%/)).toBeInTheDocument();
  });

  it("infrastructure low confidence: threshold displayed, action is HUMAN_REVIEW", () => {
    render(<Explainability />);
    fireEvent.click(screen.getByRole("button", { name: "INFRASTRUCTURE / LOW CONFIDENCE" }));
    const s = snapshot.day14.scenarios.infrastructure_low_confidence;
    expect(s.policy.action).toBe("HUMAN_REVIEW");
    const summarySection = screen.getByRole("heading", { name: /decision summary/i }).closest("section");
    expect(within(summarySection as HTMLElement).getByText("HUMAN_REVIEW")).toBeInTheDocument();
  });
});

describe("Explainability — explanation rendering", () => {
  it("renders the exact explanation summary and safety note text from the snapshot", () => {
    render(<Explainability />);
    const s = snapshot.day14.scenarios.webhook_ambiguity;
    expect(screen.getByText(s.explanation.summary)).toBeInTheDocument();
    expect(screen.getByText(s.explanation.safetyNote)).toBeInTheDocument();
  });

  it("does not fabricate a claim about which provider produced the explanation", () => {
    render(<Explainability />);
    const body = document.body.textContent ?? "";
    // The source doesn't distinguish -- the page must not either.
    expect(body).not.toMatch(/this explanation was generated by claude/i);
    expect(body).not.toMatch(/this is a deterministic explanation/i);
    expect(body).toMatch(/does not separately record which explanation provider/i);
  });
});

describe("Explainability — action-before/action-after safety invariant", () => {
  it("shows equal before/after actions for all three scenarios", () => {
    render(<Explainability />);
    for (const [label, key] of [
      ["WEBHOOK AMBIGUITY", "webhook_ambiguity"],
      ["INFRASTRUCTURE / HIGH CONFIDENCE", "infrastructure_high_confidence"],
      ["INFRASTRUCTURE / LOW CONFIDENCE", "infrastructure_low_confidence"],
    ] as const) {
      fireEvent.click(screen.getByRole("button", { name: label }));
      const s = snapshot.day14.scenarios[key];
      expect(s.safetyInvariantCheck.unchanged).toBe(true);
      const invariantSection = screen.getByRole("heading", { name: /safety invariant/i }).closest("section");
      const scoped = within(invariantSection as HTMLElement);
      expect(scoped.getByText("Action before explanation")).toBeInTheDocument();
      expect(scoped.getByText("Action after explanation")).toBeInTheDocument();
      expect(scoped.getAllByText(s.policy.action).length).toBeGreaterThanOrEqual(2);
    }
  });
});

describe("Explainability — provenance", () => {
  it("labels decision fields OBSERVED and outcome fields SIMULATED", () => {
    render(<Explainability />);
    const provenanceSection = screen.getByRole("heading", { name: /^provenance$/i }).closest("section");
    const scoped = within(provenanceSection as HTMLElement);
    expect(scoped.getByText("OBSERVED")).toBeInTheDocument();
    expect(scoped.getByText("SIMULATED")).toBeInTheDocument();
    expect(scoped.getByText("UNAVAILABLE")).toBeInTheDocument();
  });
});

describe("Explainability — WEBHOOK_AMBIGUITY primary safety case", () => {
  it("is the default scenario and shows BLOCK_RECONCILE", () => {
    render(<Explainability />);
    expect(screen.getAllByText("BLOCK_RECONCILE").length).toBeGreaterThan(0);
    expect(screen.getAllByText(/hard safety override/).length).toBeGreaterThan(0);
  });
});

describe("Explainability — no explanation parsing", () => {
  it("source contains no logic that derives an action from explanation prose", () => {
    // Complements the existing repo-wide noDecisionLogic.test.ts scan --
    // asserts specifically that this page never reads
    // `.summary`/`.safetyNote`/`.sourceNote` as a condition.
    const source = readFileSync(join(__dirname, "..", "pages", "Explainability.tsx"), "utf-8");
    expect(source).not.toMatch(/explanation\.summary\.includes/);
    expect(source).not.toMatch(/parseExplanation/);
    expect(source).not.toMatch(/summary\)\s*=>\s*.*action/i);
  });
});
