import { render, screen, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { RecoveryAnalysis } from "../pages/RecoveryAnalysis";
import { RecoveryVsSafetyChart } from "../components/recovery/RecoveryVsSafetyChart";
import { snapshot } from "../data/snapshot";

describe("RecoveryAnalysis — renders and shows all four strategies", () => {
  it("renders the page and all four strategy names", () => {
    render(<RecoveryAnalysis />);
    expect(screen.getByRole("heading", { name: /recovery, constrained by safety/i })).toBeInTheDocument();
    const comparisonSection = screen.getByRole("heading", { name: /strategy comparison/i }).closest("section");
    const scoped = within(comparisonSection as HTMLElement);
    expect(scoped.getByText("Naive Retry")).toBeInTheDocument();
    expect(scoped.getByText("Rules-only")).toBeInTheDocument();
    expect(scoped.getByText("Guardian")).toBeInTheDocument();
    expect(scoped.getByText("No Action")).toBeInTheDocument();
  });
});

describe("RecoveryAnalysis — artifact-backed values", () => {
  it("matches the live snapshot's Day 10 strategy table exactly, not hardcoded numbers", () => {
    render(<RecoveryAnalysis />);
    const g = snapshot.day10.strategyTable.GUARDIAN;
    const r = snapshot.day10.strategyTable.RULES_ONLY;
    // Sanity: Rules-only recovers more than Guardian (the actual finding).
    expect(r.simulatedAmountRecovered).toBeGreaterThan(g.simulatedAmountRecovered);
    expect(g.duplicateChargeRiskCount).toBe(0);

    const body = document.body.textContent ?? "";
    expect(body).toContain(g.transactions.toString());
  });

  it("never claims Guardian has the highest recovery or is universally superior", () => {
    render(<RecoveryAnalysis />);
    const body = document.body.textContent ?? "";
    expect(body).not.toMatch(/guardian.{0,40}(highest|best|maximum|universally optimal)/i);
    expect(body).not.toMatch(/production[- ]proven/i);
    expect(body).toMatch(/does not maximize raw recovery/i);
  });
});

describe("RecoveryAnalysis — provenance", () => {
  it("shows SIMULATED provenance visibly, not buried", () => {
    render(<RecoveryAnalysis />);
    expect(screen.getAllByText("SIMULATED").length).toBeGreaterThan(0);
    expect(
      screen.getByText(/generated by the Day 8 synthetic outcome simulator/i)
    ).toBeInTheDocument();
  });

  it("never labels simulated recovery as observed/actual/production revenue (the disclaimer may still name the rejected terms while negating them)", () => {
    render(<RecoveryAnalysis />);
    const body = document.body.textContent ?? "";
    // Forbidden: a POSITIVE claim pairing a recovered amount with these
    // terms. Allowed, and present: the honest disclaimer negating them
    // ("never observed Razorpay production recovery", "never actual
    // revenue"). Check for the specific overclaiming phrasing directly
    // rather than banning the words from co-occurring at all.
    expect(body).not.toMatch(/actual revenue recovered/i);
    expect(body).not.toMatch(/production recovery of ₹/i);
    expect(body).not.toMatch(/observed recovery of ₹/i);
    expect(body).not.toMatch(/guaranteed recovery/i);
    expect(body).toMatch(/never observed razorpay production recovery/i);
  });
});

describe("RecoveryAnalysis — Guardian zero-risk headline", () => {
  it("shows Guardian's zero duplicate-charge risk as the primary metric, not a recovery amount headline", () => {
    render(<RecoveryAnalysis />);
    expect(screen.getByRole("heading", { name: /primary safety result/i })).toBeInTheDocument();
    expect(screen.getAllByText("Duplicate-charge risk").length).toBeGreaterThan(0);
  });
});

describe("RecoveryAnalysis — WEBHOOK_AMBIGUITY population firewall (Day 9 vs Day 12)", () => {
  it("uses the 25-transaction Day 9 population, explicitly labeled, never the Day 12 1-transaction population", () => {
    render(<RecoveryAnalysis />);
    expect(snapshot.day9.webhookAmbiguity.comparison.GUARDIAN.transactionsEvaluated).toBe(25);

    expect(screen.getByText(/Day 9 test-set safety analysis — 25 transactions/)).toBeInTheDocument();
    expect(screen.getByText(/25\/25 BLOCK_RECONCILE/)).toBeInTheDocument();

    const body = document.body.textContent ?? "";
    // The Day 12 population count (1) must never appear as if it were
    // the WEBHOOK_AMBIGUITY population size on this page.
    expect(body).not.toMatch(/1\/1 BLOCK_RECONCILE/);
    expect(body).toMatch(/Day 12 incident-window population \(1 transaction\)/);
  });
});

describe("RecoveryAnalysis — recovery rate is count-based", () => {
  it("does not describe recovery rate as amount-weighted", () => {
    render(<RecoveryAnalysis />);
    const body = document.body.textContent ?? "";
    expect(body).toMatch(/count-based/i);
    expect(body).not.toMatch(/amount-weighted percentage/i);
  });
});

describe("RecoveryAnalysis — no explanation prose is parsed", () => {
  it("source contains no reference to explanation fields at all", () => {
    // RecoveryAnalysis.tsx must not import or read anything from
    // snapshot.day14.scenarios[*].explanation -- it is a Day 9/10
    // evidence page, not an explanation page.
    const source = RecoveryAnalysis.toString();
    expect(source).not.toMatch(/\.explanation\b/);
    expect(source).not.toMatch(/safetyNote/);
    expect(source).not.toMatch(/sourceNote/);
  });
});

describe("RecoveryAnalysis — no ground-truth field drives rendering", () => {
  it("does not reference actual_root_cause or actualRootCause anywhere", () => {
    const source = RecoveryAnalysis.toString();
    expect(source).not.toMatch(/actual_root_cause/);
    expect(source).not.toMatch(/actualRootCause/);
  });
});

describe("RecoveryAnalysis — seed sensitivity uses only confirmed data", () => {
  it("shows exactly the seeds present in the live snapshot, no invented seeds", () => {
    render(<RecoveryAnalysis />);
    const seeds = [String(snapshot.day10.primarySeed), ...snapshot.day10.sensitivitySeeds.map(String)];
    expect(seeds).toEqual(["42", "43", "44"]);
    const seedSection = screen.getByRole("heading", { name: /seed sensitivity/i }).closest("section");
    const scoped = within(seedSection as HTMLElement);
    for (const seed of seeds) {
      expect(scoped.getByText(`Seed ${seed}`)).toBeInTheDocument();
    }
  });

  it("Guardian duplicate-charge risk is zero for every seed shown", () => {
    const seeds = [String(snapshot.day10.primarySeed), ...snapshot.day10.sensitivitySeeds.map(String)];
    const seedSensitivity: Record<string, { GUARDIAN: { duplicateChargeRiskCount: number } }> = snapshot.day10.seedSensitivity;
    for (const seed of seeds) {
      expect(seedSensitivity[seed].GUARDIAN.duplicateChargeRiskCount).toBe(0);
    }
  });
});

describe("RecoveryAnalysis — root-cause data is artifact-backed, not fabricated", () => {
  it("renders all six root causes from the live snapshot", () => {
    render(<RecoveryAnalysis />);
    const rootCauseSection = screen.getByRole("heading", { name: /root-cause breakdown/i }).closest("section");
    const scoped = within(rootCauseSection as HTMLElement);
    for (const rc of Object.keys(snapshot.day10.rootCauseTable)) {
      expect(scoped.getAllByText(rc).length).toBeGreaterThan(0);
    }
  });

  it("CARD_DECLINE + INSUFFICIENT_FUNDS combined count matches the live snapshot (99 transactions)", () => {
    render(<RecoveryAnalysis />);
    const combined = snapshot.day10.combinedCardDeclineInsufficientFunds.GUARDIAN;
    expect(combined.transactions).toBe(99);
    expect(screen.getByText(new RegExp(`${combined.transactions} transactions`))).toBeInTheDocument();
  });

  it("INFRASTRUCTURE Guardian action split matches the live snapshot (43 DEFER_RETRY / 12 HUMAN_REVIEW)", () => {
    render(<RecoveryAnalysis />);
    const infra = snapshot.day10.rootCauseTable.INFRASTRUCTURE.GUARDIAN;
    expect(infra.actionDistribution.DEFER_RETRY).toBe(43);
    expect(infra.actionDistribution.HUMAN_REVIEW).toBe(12);
    expect(screen.getByText(/43 DEFER_RETRY/)).toBeInTheDocument();
    expect(screen.getByText(/12 HUMAN_REVIEW/)).toBeInTheDocument();
  });

  it("uses the actual policy threshold from the snapshot, not a hardcoded 0.75", () => {
    render(<RecoveryAnalysis />);
    expect(snapshot.day12.infrastructureConfidenceThreshold).toBe(0.75);
    expect(screen.getByText(/75% confidence threshold/)).toBeInTheDocument();
  });
});

describe("RecoveryVsSafetyChart — aggregate points only", () => {
  it("renders exactly one point per strategy with an accessible data table", () => {
    render(
      <RecoveryVsSafetyChart
        points={[
          { strategy: "Naive Retry", simulatedAmountRecovered: 205427.28, duplicateChargeRiskCount: 12, recoveryRate: 0.2975 },
          { strategy: "Rules-only", simulatedAmountRecovered: 238230.16, duplicateChargeRiskCount: 3, recoveryRate: 0.3388 },
          { strategy: "Guardian", simulatedAmountRecovered: 193316.24, duplicateChargeRiskCount: 0, recoveryRate: 0.2893, isGuardian: true },
          { strategy: "No Action", simulatedAmountRecovered: 0, duplicateChargeRiskCount: 0, recoveryRate: 0 },
        ]}
      />
    );
    expect(screen.getByRole("img", { name: /recovery vs safety, by strategy/i })).toBeInTheDocument();
    const table = screen.getByRole("table");
    const rows = within(table).getAllByRole("row");
    expect(rows).toHaveLength(5); // header + 4 strategies
  });

  it("shows DATA UNAVAILABLE instead of a fabricated point when data is invalid", () => {
    render(
      <RecoveryVsSafetyChart
        points={[{ strategy: "Broken", simulatedAmountRecovered: NaN, duplicateChargeRiskCount: -1, recoveryRate: 0 }]}
      />
    );
    expect(screen.getByText("DATA UNAVAILABLE")).toBeInTheDocument();
  });
});
