/**
 * Recovery Guardian — Day 15 Frontend Data Snapshot
 *
 * GENERATED FILE. Do not hand-edit.
 *
 * Generated by: scripts/generate_frontend_snapshot.py
 * Source artifacts:
 *   - experiments/results/day9_seed_42_aggregate.json  (Day 9, frozen)
 *   - experiments/results/day12_incident_demo.json      (Day 12, frozen)
 *
 * Every numeric value below is copied verbatim (rounded for display
 * only) from the authoritative artifacts above — nothing here is
 * recomputed, re-derived, or invented by this project's frontend. See
 * scripts/generate_frontend_snapshot.py's module docstring for the full
 * data-plumbing contract (Day 15 Milestone 1, section 22A).
 *
 * Regenerate with:
 *   python3 scripts/generate_frontend_snapshot.py
 */

export const SNAPSHOT_GENERATED_AT = "2026-08-23T12:20:47.073409+00:00";

export const snapshot = {
  "generatedAt": "2026-08-23T12:20:47.073409+00:00",
  "sourceArtifacts": {
    "day9": "experiments/results/day9_seed_42_aggregate.json",
    "day12": "experiments/results/day12_incident_demo.json"
  },
  "day9": {
    "experimentSeed": 42,
    "transactionCount": 242,
    "strategyComparison": {
      "GUARDIAN": {
        "simulatedAmountRecovered": 193316.24,
        "recoveryRate": 0.2892561983471074,
        "duplicateChargeRiskCount": 0,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      },
      "RULES_ONLY": {
        "simulatedAmountRecovered": 238230.16,
        "recoveryRate": 0.33884297520661155,
        "duplicateChargeRiskCount": 3,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      },
      "NAIVE_RETRY": {
        "simulatedAmountRecovered": 205427.28,
        "recoveryRate": 0.2975206611570248,
        "duplicateChargeRiskCount": 12,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      },
      "NO_ACTION": {
        "simulatedAmountRecovered": 0.0,
        "recoveryRate": 0.0,
        "duplicateChargeRiskCount": 0,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      }
    },
    "webhookAmbiguity": {
      "comparison": {
        "GUARDIAN": {
          "recoveryRate": 0.0,
          "duplicateChargeRiskCount": 0,
          "transactionsEvaluated": 25,
          "totalAmountAtRisk": 63716.2
        },
        "RULES_ONLY": {
          "recoveryRate": 0.2,
          "duplicateChargeRiskCount": 3,
          "transactionsEvaluated": 25,
          "totalAmountAtRisk": 63716.2
        },
        "NAIVE_RETRY": {
          "recoveryRate": 0.68,
          "duplicateChargeRiskCount": 12,
          "transactionsEvaluated": 25,
          "totalAmountAtRisk": 63716.2
        }
      },
      "guardianBlockReconcileCount": 25
    },
    "guardianDuplicateChargeRiskBySeed": {
      "42": 0,
      "43": 0,
      "44": 0
    }
  },
  "day12": {
    "incidentWindow": {
      "start": "2026-08-15T22:10:00",
      "end": "2026-08-15T22:40:00"
    },
    "incidentCount": 110,
    "classDistribution": {
      "INFRASTRUCTURE": 73,
      "CARD_DECLINE": 9,
      "INSUFFICIENT_FUNDS": 15,
      "OTP_TIMEOUT": 9,
      "USER_ABANDONMENT": 3,
      "WEBHOOK_AMBIGUITY": 1
    },
    "splitMembership": {
      "trainCount": 79,
      "validationCount": 13,
      "testCount": 18
    },
    "fullWindowInfrastructure": {
      "correct": 73,
      "total": 73
    },
    "heldOutTestInfrastructure": {
      "correct": 15,
      "total": 15
    },
    "webhookAmbiguitySafety": {
      "caseCount": 1,
      "blockReconcileCount": 1,
      "deferRetryCount": 0,
      "safetyPass": true
    }
  }
} as const;

export type Snapshot = typeof snapshot;
