/**
 * Recovery Guardian — Day 15 Frontend Data Snapshot
 *
 * GENERATED FILE. Do not hand-edit.
 *
 * Generated by: scripts/generate_frontend_snapshot.py
 * Source artifacts:
 *   - experiments/results/day9_seed_42_aggregate.json  (Day 9, frozen)
 *   - experiments/results/day12_incident_demo.json      (Day 12, frozen)
 *   - experiments/results/day14_demo.json               (Day 14, frozen)
 *
 * Every numeric value below is copied verbatim (rounded for display
 * only) from the authoritative artifacts above — nothing here is
 * recomputed, re-derived, or invented by this project's frontend. See
 * scripts/generate_frontend_snapshot.py's module docstring for the full
 * data-plumbing contract (Day 15 Milestone 1, section 22A).
 *
 * Regenerate with:
 *   python3 scripts/generate_frontend_snapshot.py
 */

export const SNAPSHOT_GENERATED_AT = "2026-08-23T12:43:41.025538+00:00";

export const snapshot = {
  "generatedAt": "2026-08-23T12:43:41.025538+00:00",
  "sourceArtifacts": {
    "day9": "experiments/results/day9_seed_42_aggregate.json",
    "day12": "experiments/results/day12_incident_demo.json",
    "day14": "experiments/results/day14_demo.json"
  },
  "day9": {
    "experimentSeed": 42,
    "transactionCount": 242,
    "strategyComparison": {
      "GUARDIAN": {
        "simulatedAmountRecovered": 193316.24,
        "recoveryRate": 0.2892561983471074,
        "duplicateChargeRiskCount": 0,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      },
      "RULES_ONLY": {
        "simulatedAmountRecovered": 238230.16,
        "recoveryRate": 0.33884297520661155,
        "duplicateChargeRiskCount": 3,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      },
      "NAIVE_RETRY": {
        "simulatedAmountRecovered": 205427.28,
        "recoveryRate": 0.2975206611570248,
        "duplicateChargeRiskCount": 12,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      },
      "NO_ACTION": {
        "simulatedAmountRecovered": 0.0,
        "recoveryRate": 0.0,
        "duplicateChargeRiskCount": 0,
        "transactionsEvaluated": 242,
        "totalAmountAtRisk": 677213.78
      }
    },
    "webhookAmbiguity": {
      "comparison": {
        "GUARDIAN": {
          "recoveryRate": 0.0,
          "duplicateChargeRiskCount": 0,
          "transactionsEvaluated": 25,
          "totalAmountAtRisk": 63716.2
        },
        "RULES_ONLY": {
          "recoveryRate": 0.2,
          "duplicateChargeRiskCount": 3,
          "transactionsEvaluated": 25,
          "totalAmountAtRisk": 63716.2
        },
        "NAIVE_RETRY": {
          "recoveryRate": 0.68,
          "duplicateChargeRiskCount": 12,
          "transactionsEvaluated": 25,
          "totalAmountAtRisk": 63716.2
        }
      },
      "guardianBlockReconcileCount": 25
    },
    "guardianDuplicateChargeRiskBySeed": {
      "42": 0,
      "43": 0,
      "44": 0
    }
  },
  "day12": {
    "incidentWindow": {
      "start": "2026-08-15T22:10:00",
      "end": "2026-08-15T22:40:00"
    },
    "incidentCount": 110,
    "classDistribution": {
      "INFRASTRUCTURE": 73,
      "CARD_DECLINE": 9,
      "INSUFFICIENT_FUNDS": 15,
      "OTP_TIMEOUT": 9,
      "USER_ABANDONMENT": 3,
      "WEBHOOK_AMBIGUITY": 1
    },
    "splitMembership": {
      "trainCount": 79,
      "validationCount": 13,
      "testCount": 18
    },
    "fullWindowInfrastructure": {
      "correct": 73,
      "total": 73
    },
    "heldOutTestInfrastructure": {
      "correct": 15,
      "total": 15
    },
    "webhookAmbiguitySafety": {
      "caseCount": 1,
      "blockReconcileCount": 1,
      "deferRetryCount": 0,
      "safetyPass": true
    }
  },
  "day14": {
    "scenarios": {
      "webhook_ambiguity": {
        "scenarioLabel": "Primary safety scenario \u2014 WEBHOOK_AMBIGUITY",
        "transactionId": "txn_000536_9f0ef7",
        "paymentEvent": {
          "amount": 3173.84,
          "paymentMethod": "upi",
          "failureCode": "gateway_timeout",
          "retryCount": 0,
          "webhookDelaySeconds": 10.38,
          "incidentActive": false
        },
        "prediction": {
          "rootCause": "WEBHOOK_AMBIGUITY",
          "probability": 0.938427,
          "modelVersion": "root-cause-logreg-calibrated-v1"
        },
        "policy": {
          "action": "BLOCK_RECONCILE",
          "reason": "WEBHOOK_STATE_UNKNOWN",
          "version": "rules-v1",
          "thresholdIfApplicable": null
        },
        "outcome": {
          "recovered": false,
          "amountRecovered": 0.0,
          "duplicateChargeRisk": false,
          "provenance": "SIMULATED"
        },
        "safetyInvariantCheck": {
          "actionBeforeExplanation": "BLOCK_RECONCILE",
          "actionAfterExplanation": "BLOCK_RECONCILE",
          "unchanged": true
        }
      },
      "infrastructure_high_confidence": {
        "scenarioLabel": "Secondary scenario \u2014 INFRASTRUCTURE, high confidence",
        "transactionId": "txn_001453_f609ab",
        "paymentEvent": {
          "amount": 731.93,
          "paymentMethod": "upi",
          "failureCode": "internal_error",
          "retryCount": 0,
          "webhookDelaySeconds": 5.31,
          "incidentActive": false
        },
        "prediction": {
          "rootCause": "INFRASTRUCTURE",
          "probability": 0.981901,
          "modelVersion": "root-cause-logreg-calibrated-v1"
        },
        "policy": {
          "action": "DEFER_RETRY",
          "reason": "INFRA_CLUSTER_HIGH",
          "version": "rules-v1",
          "thresholdIfApplicable": 0.75
        },
        "outcome": {
          "recovered": true,
          "amountRecovered": 731.93,
          "duplicateChargeRisk": false,
          "provenance": "SIMULATED"
        },
        "safetyInvariantCheck": {
          "actionBeforeExplanation": "DEFER_RETRY",
          "actionAfterExplanation": "DEFER_RETRY",
          "unchanged": true
        }
      },
      "infrastructure_low_confidence": {
        "scenarioLabel": "Secondary scenario \u2014 INFRASTRUCTURE, low confidence",
        "transactionId": "txn_001247_939b14",
        "paymentEvent": {
          "amount": 2478.11,
          "paymentMethod": "wallet",
          "failureCode": "gateway_timeout",
          "retryCount": 1,
          "webhookDelaySeconds": 7.89,
          "incidentActive": false
        },
        "prediction": {
          "rootCause": "INFRASTRUCTURE",
          "probability": 0.696458,
          "modelVersion": "root-cause-logreg-calibrated-v1"
        },
        "policy": {
          "action": "HUMAN_REVIEW",
          "reason": "LOW_MODEL_CONFIDENCE",
          "version": "rules-v1",
          "thresholdIfApplicable": 0.75
        },
        "outcome": {
          "recovered": false,
          "amountRecovered": 0.0,
          "duplicateChargeRisk": false,
          "provenance": "SIMULATED"
        },
        "safetyInvariantCheck": {
          "actionBeforeExplanation": "HUMAN_REVIEW",
          "actionAfterExplanation": "HUMAN_REVIEW",
          "unchanged": true
        }
      }
    }
  }
} as const;

export type Snapshot = typeof snapshot;
